[build]
  useResourceCacheWhen = "fallback"

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[pagination]
  disableAliases = false
  pagerSize = 3
  path = 'pages'

# Math support.

[markup.goldmark.extensions.passthrough]
  enable = true

[markup.goldmark.extensions.passthrough.delimiters]
  block = [['\[', '\]'], ['$$', '$$']]
  inline = [['\(', '\)']]

[params]
  math = true

